### ISSUE TITLE
severe bug with DependencyNotifyingDomFacade reporting too many nodes

### ISSUE THREAD

**Issue by JoernT** [Jinntec/Fore#111]
``` 
    <fx-fore>
        <fx-model>
            <fx-instance id="default">
                <data>
                    <prerequisite name="targetServer" description="checking target server...">checking</prerequisite>
                    <prerequisite name="github" description="checking github...">checking</prerequisite>
                    <prerequisite name="airtable" description="checking airtable...">checking</prerequisite>
                    <prerequisite name="filesystem" description="checking the filesystem...">checking</prerequisite>
                    <prerequisite name="tuttle" description="checking Tuttle...">checking</prerequisite>
                    <prerequisite name="proceed" description="checking if all prerequisites are matched...">checking</prerequisite>
                </data>
            </fx-instance>

            <fx-bind ref="prerequisite[5]" calculate="//prerequisite[1]"></fx-bind>
        </fx-model>

        <fx-output ref="//prerequisite[5]" label="calculated value">

        </fx-output>
    </fx-fore>

```

will crash the browser window due to creating circular dependencies in the graph and an endless loop.

Error occurs in this block of code:
```
  _getReferencesForProperty(propertyExpr) {
    if (propertyExpr) {
      const touchedNodes = new Set();
      const domFacade = new DependencyNotifyingDomFacade(otherNode => touchedNodes.add(otherNode));
      this.nodeset.forEach(node => {
        evaluateXPathToString(propertyExpr, node, this.getOwnerForm(), domFacade);
      });

      return Array.from(touchedNodes.values());
    }
    return [];
  }
```

which returns too many references.

Other similar use cases bring up other errors.

**Comment by JoernT** [comment]
btw - that does not mean that `calculate` is not working in general - the subgraph demo and other calculation demos work.

**Comment by DrRataplan** [comment]
First thought is that FontoXPath is not properly optimizing `//prerequisite[1]`. It's expanding it to `descendant-or-self::node()/(child::prerequisite[1])`. Likely breaking any kind of lazy evaluation it usually does.

That, or the `//prerequisite[5]`, which kind-of does have a dependency on the (existence of) earlier `prerequisite` elements, but not on its content.

**Comment by DrRataplan** [comment]
Hm. I'm not liking this.

Turns out we are traversing _into_ all those prerequisites to see whether there is a new prerequisite _in_ them. It's doing this because the XPath `//prerequisites[1]` has to return those prerequisites as well.

See this playground to see what I'm talking about: https://xpath.playground.fontoxml.com/?state=H4sIAJyTMGIAA52SzW6DMBCEX2W15wjaa0R5h6q9lR4cvIFVsaHrJUoU5d3rgFCTSOTvZms%2Bz2jXs0fXWsLlywI3RtisGgq4xP0BF7h1TTxm1qjJCw%2BQdUJCvz0HVgJvHL0VqEYq0g%2BSDUmBYCmUwp1y66NY1lT%2BsK9gpCAMWJIkBeaTduaa5ll6ep%2FPrVjrfjWfOOoXUXd6GxY9bmLefSKe819z3PIuKLkrG6sJ%2FrnncrRXvTbF56CP3hff8GhUJ21JZOezeA2maeD0bQAjBM5ohOyNCbN0qOGxle89yS4WMz1jvl6%2Fo1i2XmmrE4KHPxCoF6PgAgAA

Full reason why XPath does this is because the `//x` query is expanded to `/descendant-or-self::node()/child::x`. And that `[1]` part binds only to the `child::x` part: return all _first_ elements called `x`. Not the first one overall in document order.

We'll need to dust off the the idea that the spec introduces: distinction between nodes we're returning and those we are 'just passing'.
