### ISSUE TITLE
Character encoding/display issue in Chrome

### ISSUE THREAD

**Issue by timathom** [Jinntec/Fore#153]
### Discussed in #152.

I have text in Russian that has been transliterated and contains diacritics. Using this instance data (inline or loaded from file):

```
<catalog yes="true" no="false" maybe="false" confidence="0" bib="811932">
  <a href="https://search.library.yale.edu/catalog/811932" target="_blank">Semʹi︠a︡ Ulʹi︠a︡novykh : tetralogii︠a︡ ; Ocherki i statʹi o Lenine : 1935-1981 / Mariėtta Shagini︠a︡n.</a>
</catalog>
```

And this form:

```
<fx-fore>
  <fx-model>
    <!-- Instance data -->
    <fx-instance src="catalog.xml"></fx-instance>
    <!-- /Instance data -->
  </fx-model>
  <fx-repeat id="repeat-catalog" ref=".">
    <template>
      <div class="row">
        <div class="catalog-entry col">
          <a href="{a/@href}" target="_blank">
            <fx-output value="a"></fx-output>
          </a>         
        </div>
      </div>
    </template>
  </fx-repeat>
  <fx-inspector open="true"></fx-inspector>
</fx-fore>

```

The diacritics display correctly in Firefox, but not in Chrome.

**Comment by JoernT** [comment]
@timathom could you kindly provide the catalog.xml please?

**Comment by JoernT** [comment]
So clearly it has to deal with Chromes' usage of fonts and it not related with Fore. 

Setting an compatible font explicitly fixes the issue in Chrome and Safari like is shown in the file 'demo/diacritics.html'. 

A related [google fonts issue](https://github.com/google/fonts/issues/1702).

Affected by this issue:
* Chrome on Mac
* Safari on Mac
Other platforms not tested by likely also affected. 

Firefox is working properly.

This issue is beyond the scope of Fore but special precaution obviously is necessary when dealing with diacritics.
