### ISSUE TITLE
problem with camelCase element names

### ISSUE THREAD

**Issue by pherk** [Jinntec/Fore#284]
migrating an old betterform app to Fore I stumbled over a problem with camelCase.
Neither lower camelCase nor upper camelCase names seem to be ok.

~~~
                    <rrule>
                        <freq value="daily"/>
                        <byWeekNo value="odd"/>
                        <byDay value="Mo,Mi"/>
                    </rrule>
~~~

the elements with camelCase are rendered but labeled as nonrelevant when used in a fx-control.
Is this a feature or a bug?
I can provide a MWE if needed.

**Comment by JoernT** [comment]
This is not a bug but due to HTML being all lowercase - you can write mixed case but the HTML parser will convert all to lowercase. Fore is using the inline markup to create an in-memory clone parsed as XML. Inline markup should be considered just a convenience for the easier cases when you don't need all bells and whistles of XML.

When you want to use XML you have to load it via `<fx-instance src="...">` or load it via a submission. In that case you get a full-blown XML file.
